version: '3'
services: 
    nginx:
        build: ./requirements/nginx
        image: nginx
        container_name: nginx
        ports:
            - "443:443"
        restart: always
        volumes:
            - wp_data:/var/www/html/
        depends_on:
            - wordpress
        networks:
            - dakhla_city

    wordpress:
        build: ./requirements/wordpress
        image: wordpress
        container_name: wordpress
        ports:
            - "9000"
        restart: always
        volumes:
            - wp_data:/var/www/html/
        networks:
            - dakhla_city
        env_file:
            - .env
        depends_on:
            - mariadb

    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        container_name: mariadb
        ports:
            - "3306"
        restart: always
        networks:
            - dakhla_city
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/mysql

volumes:
    wp_data:
        driver: local
        driver_opts:
            type: none
            device: "/home/ael-azra/data/wordpress"
            o: bind
    db_data:
        driver: local
        driver_opts:
            type: none
            device: "/home/ael-azra/data/mysql"
            o: bind

networks:
    dakhla_city:
        name: dakhla_city
        driver: bridge